### Qui Quadrado

#### Importando bibliotecas

In [4]:
import numpy as np
from scipy.stats import chi2_contingency

#### Criação de matriz com os dados e execução do teste

In [6]:
novela = np.array([[19, 6], [43, 32]])
novela

array([[19,  6],
       [43, 32]])

#### Segundo valor é o pvalue
valor de p é maior que 0,05 não há evidência significativa (hipótese nula): não há diferença significativa 

In [7]:
chi2_contingency(novela)

(2.037351443123939,
 0.15347667161786666,
 1,
 array([[15.5,  9.5],
        [46.5, 28.5]]))

In [8]:
novela2 = np.array([[22, 3], [43, 32]])
novela2

array([[22,  3],
       [43, 32]])

Agora valor de p menor que 0,05, podemos rejeitar a hipótese nula da em favor da hipótese alternativa: há diferença significativa

In [9]:
chi2_contingency(novela2)

(6.461538461538461,
 0.011023416388221425,
 1,
 array([[16.25,  8.75],
        [48.75, 26.25]]))