## Importa Nunpy

In [24]:
import numpy as np

## Criar matriz unidimencional

In [25]:
mt = np.array([12, 34, 58, 23, 98])
print(mt)
print(type(mt))

[12 34 58 23 98]
<class 'numpy.ndarray'>


##  Criar array com um tipo específico

In [26]:
mtFlot = np.array([1, 2, 3], dtype=np.float64)
print(mtFlot)
print(type(mtFlot))
mtInt = np.array([4, 5, 6], dtype=np.int32)
print(mtInt)
print(type(mtInt))

[1. 2. 3.]
<class 'numpy.ndarray'>
[4 5 6]
<class 'numpy.ndarray'>


## Mudar o tipo do array

In [27]:
mtNew = np.array([1.4, 1.8, 2.9, 4.3])
print(mtNew)

[1.4 1.8 2.9 4.3]


##### Quando transformamos de float para int os valores são truncados

In [28]:
mtNewInt = mtNew.astype(np.int32)
print(mtNewInt)

[1 1 2 4]


#### Podemos fazer o inverso também

In [29]:
mtNewFlot = mtNewInt.astype(np.float64)
print(mtNewFlot)

[1. 1. 2. 4.]


## Arrays tipificados

#### Empty -> Significa que são iniciados, não que são vazios

In [30]:
vazio = np.empty([3, 2], dtype=int)
print(vazio)

[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]]


#### Zeros -> Cria matriz com valores zero

In [31]:
zeros = np.zeros([4, 3])
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### Ones -> Cria matriz com valores um

In [32]:
ones = np.ones([3, 3])
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### Eye -> Cria matrizquadrada com diagonal principal com valores 1 e os outros como 0

In [33]:
eye = np.eye(5)
print(eye)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Matrizes

#### Matriz bidimencional

In [34]:
mtb = np.array([[7, 2 , 6], [8, 5 ,3], [4, 1, 0]])
print(mtb)

[[7 2 6]
 [8 5 3]
 [4 1 0]]


## Valores aleatórios entre zero e um

In [35]:
randomPos = np.random.random((5))
print(randomPos)

[0.41521303 0.04604638 0.01143216 0.4699172  0.93416245]


#### Valores aleatórios contendo números negativos

In [36]:
randomNot = np.random.randn((5))
print(randomNot)

[ 0.16291717 -0.08721083 -0.51900788  1.04457138  1.86603651]


#### Matriz 3x4 com números aleatórios multiplicados por 10

In [38]:
mtMul = (10 * np.random.random((3, 4)))
print(mtMul)

[[4.85003426 8.4233936  2.81647354 9.13023582]
 [7.87387793 4.53183734 2.95007276 1.43290796]
 [8.21189616 7.49539152 9.13543694 9.99249427]]


## Outra forma de gerar números aleatórios usando semente

In [40]:
rng = np.random.default_rng(1)
randomRng = rng.random(5)
print(randomRng)

[0.51182162 0.9504637  0.14415961 0.94864945 0.31183145]


#### Gerando inteiros

In [42]:
randonInt = rng.integers(10, size=(3, 4))
print(randonInt)

[[8 4 2 8]
 [2 4 6 5]
 [0 0 8 7]]
