## Importa Nunpy

In [2]:
import numpy as np

## Criar matriz unidimencional

In [3]:
mt = np.array([12, 34, 58, 23, 98])
print(mt)
print(type(mt))

[12 34 58 23 98]
<class 'numpy.ndarray'>


##  Criar array com um tipo específico

In [4]:
mtFlot = np.array([1, 2, 3], dtype=np.float64)
print(mtFlot)
print(type(mtFlot))
mtInt = np.array([4, 5, 6], dtype=np.int32)
print(mtInt)
print(type(mtInt))

[1. 2. 3.]
<class 'numpy.ndarray'>
[4 5 6]
<class 'numpy.ndarray'>


## Mudar o tipo do array

In [5]:
mtNew = np.array([1.4, 1.8, 2.9, 4.3])
print(mtNew)

[1.4 1.8 2.9 4.3]


##### Quando transformamos de float para int os valores são truncados

In [6]:
mtNewInt = mtNew.astype(np.int32)
print(mtNewInt)

[1 1 2 4]


#### Podemos fazer o inverso também

In [7]:
mtNewFlot = mtNewInt.astype(np.float64)
print(mtNewFlot)

[1. 1. 2. 4.]


## Arrays

#### Empty -> Significa que são iniciados, não que são vazios

In [8]:
vazio = np.empty([3, 2], dtype=int)
print(vazio)

[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]]


#### Unique -> Remove as repetições

In [9]:
array = np.array([11, 12, 13, 14, 11, 15, 13, 14, 11, 16, 12,17])
array = np.unique(array)
print(array)

[11 12 13 14 15 16 17]


## Extração de elementos

In [10]:
array = np.array([1, 2, 3, 4, 5])

#### Mostra elemento da posição 2

In [11]:
print(array[2])

3


#### Mostra array da posição 0 até a posição 2-1

In [12]:
print(array[0:2])

[1 2]


#### Mostra array  da posição 2 até o final

In [13]:
print(array[2:])

[3 4 5]


#### Mostra array da antepenúltima posição até o final

In [14]:
print(array[-3:])

[3 4 5]


## Extração de linhas e colunas

In [15]:
array = np.array([[1, 2], [4, 3], [5, 7]])

#### Primeira linha de todas as colunas

In [38]:
l1 = array[0, :]
print(l1)

[1 2]


#### Segunda linha de todas as colunas

In [37]:
l2 = array[1, :]
print(l2)

[4 3]


#### Terceira linha de todas as colunas

In [39]:
l3 = array[2, :]
print(l3)

[5 7]


#### Todas as linhas da primeira coluna

In [40]:
lall1 = array[:, 0]
print(lall1)

[1 4 5]


#### Todas as linhas da segunda coluna

In [41]:
laal2 = array[:, 1]
print(laal2)

[2 3 7]


## Matrizes

#### Zeros -> Cria matriz com valores zero

In [16]:
zeros = np.zeros([4, 3])
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### Ones -> Cria matriz com valores um

In [17]:
ones = np.ones([3, 3])
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### Eye -> Cria matrizquadrada com diagonal principal com valores 1 e os outros como 0

In [18]:
eye = np.eye(5)
print(eye)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### Matriz bidimencional

In [19]:
mtb = np.array([[7, 2 , 6], [8, 5 ,3], [4, 1, 0]])
print(mtb)

[[7 2 6]
 [8 5 3]
 [4 1 0]]


#### Mostra elemento específico da matriz

In [20]:
print(mtb[0][1])

2


#### Mostra o tamanho das dimenções da matriz

In [21]:
print(mtb.shape)

(3, 3)


## Funções matemáticas

#### Mostra maior valor da matriz

In [22]:
print(mtb.max())

8


#### Mostra menor valor da matriz

In [23]:
print(mtb.min())

0


#### Mostra soma dos elementos da matriz

In [24]:
print(mtb.sum())

36


#### Mostra média dos valores dos elementos da matriz

In [25]:
print(mtb.mean())

4.0


#### Mostra o valor do desvio padrão (standard deviation) dos valores da matriz

In [26]:
print(mtb.std())

2.581988897471611


#### Raiz quadrada

In [27]:
print(np.sqrt(mtb))

[[2.64575131 1.41421356 2.44948974]
 [2.82842712 2.23606798 1.73205081]
 [2.         1.         0.        ]]


#### Exponencial

In [28]:
print(np.exp(mtb))

[[1.09663316e+03 7.38905610e+00 4.03428793e+02]
 [2.98095799e+03 1.48413159e+02 2.00855369e+01]
 [5.45981500e+01 2.71828183e+00 1.00000000e+00]]


## Adição e multiplicação de matrizes

In [47]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[2, 2], [1, 1]])


#### Soma

In [48]:
print(resultado := (array1 + array2))

[[3 4]
 [4 5]]


#### Multiplicação

In [49]:
print(resultado := (array1 * array2))

[[2 4]
 [3 4]]


#### Exemplo com quantidades diferentes

In [55]:
array3 = np.array([[2, 3], [ 3, 4], [2, 5]])
array4 = np.array([1, 2])
print(resultado := (array3 * array4))

[[ 2  6]
 [ 3  8]
 [ 2 10]]


## Valores aleatórios entre zero e um

In [29]:
randomPos = np.random.random((5))
print(randomPos)

[0.21181681 0.62269716 0.23575935 0.85719723 0.17865331]


#### Valores aleatórios contendo números negativos

In [30]:
randomNot = np.random.randn((5))
print(randomNot)

[ 1.27569351 -1.05169509 -0.84520524  1.54260692 -0.30855728]


#### Matriz 3x4 com números aleatórios multiplicados por 10

In [31]:
mtMul = (10 * np.random.random((3, 4)))
print(mtMul)

[[8.35264265 3.08530467 9.34561155 0.97821018]
 [3.20180911 3.91180536 3.95976186 7.35898631]
 [7.83146232 9.87095703 6.36863583 7.07195612]]


## Outra forma de gerar números aleatórios usando semente

In [32]:
rng = np.random.default_rng(1)
randomRng = rng.random(5)
print(randomRng)

[0.51182162 0.9504637  0.14415961 0.94864945 0.31183145]


#### Gerando inteiros

In [33]:
randonInt = rng.integers(10, size=(3, 4))
print(randonInt)

[[8 4 2 8]
 [2 4 6 5]
 [0 0 8 7]]
