## Importa Nunpy

In [8]:
import numpy as np

## Criar matriz unidimencional

In [9]:
mt = np.array([12, 34, 58, 23, 98])
print(mt)
print(type(mt))

[12 34 58 23 98]
<class 'numpy.ndarray'>


##  Criar array com um tipo específico

In [10]:
mtflot = np.array([1, 2, 3], dtype=np.float64)
print(mtflot)
print(type(mtflot))
mtint = np.array([4, 5, 6], dtype=np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[4 5 6]
<class 'numpy.ndarray'>


## Mudar o tipo do array

In [11]:
mtnew = np.array([1.4, 1.8, 2.9, 4.3])
print(mtnew)

[1.4 1.8 2.9 4.3]


##### Quando transformamos de float para int os valores são truncados

In [12]:
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[1 1 2 4]


#### Podemos fazer o inverso também

In [14]:
mtnewflot = mtnewint.astype(np.float64)
print(mtnewflot)

[1. 1. 2. 4.]


## Arrays tipificados

#### Empty -> Significa que são iniciados, não que são vazios

In [17]:
vazio = np.empty([3, 2], dtype=int)
print(vazio)

[[         0 1074790400]
 [         0 1075052544]
 [         0 1075314688]]


#### Zeros -> Cria matrix com valores zero

In [18]:
zeros = np.zeros([4, 3])
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Matrizes

#### Matriz bidimencional

In [16]:
mtb = np.array([[7, 2 , 6], [8, 5 ,3], [4, 1, 0]])
print(mtb)

[[7 2 6]
 [8 5 3]
 [4 1 0]]
