## Numpy
___

In [71]:
import numpy as np

## Criar matriz unidimencional

In [119]:
print(mt := np.array([12, 34, 58, 23, 98]))
print(type(mt))

[12 34 58 23 98]
<class 'numpy.ndarray'>


##  Criar array com um tipo específico

In [118]:
print(mtFlot := np.array([1, 2, 3], dtype=np.float64))
print(type(mtFlot))
print(mtInt := np.array([4, 5, 6], dtype=np.int32))
print(type(mtInt))

[1. 2. 3.]
<class 'numpy.ndarray'>
[4 5 6]
<class 'numpy.ndarray'>


## Mudar o tipo do array

In [117]:
print(mtNew := np.array([1.4, 1.8, 2.9, 4.3]))

[1.4 1.8 2.9 4.3]


##### Quando transformamos de float para int os valores são truncados

In [116]:
print(mtNewInt := mtNew.astype(np.int32))

[1 1 2 4]


#### Podemos fazer o inverso também

In [115]:
print(mtNewFlot := mtNewInt.astype(np.float64))

[1. 1. 2. 4.]


## Arrays

#### Empty -> Significa que são iniciados, não que são vazios

In [114]:
print(result := np.empty([3, 2], dtype=int))

[[ 2  6]
 [ 3  8]
 [ 2 10]]


#### Unique -> Remove as repetições

In [78]:
array = np.array([11, 12, 13, 14, 11, 15, 13, 14, 11, 16, 12,17])
array = np.unique(array)
print(array)

[11 12 13 14 15 16 17]


## Extração de elementos

In [79]:
array = np.array([1, 2, 3, 4, 5])

#### Mostra elemento da posição 2

In [80]:
print(array[2])

3


#### Mostra array da posição 0 até a posição 2-1

In [81]:
print(array[0:2])

[1 2]


#### Mostra array  da posição 2 até o final

In [82]:
print(array[2:])

[3 4 5]


#### Mostra array da antepenúltima posição até o final

In [83]:
print(array[-3:])

[3 4 5]


## Extração de linhas e colunas

In [84]:
array = np.array([[1, 2], [4, 3], [5, 7]])

#### Primeira linha de todas as colunas

In [85]:
print(l1 := array[0, :])

[1 2]


#### Segunda linha de todas as colunas

In [86]:
print(l2 := array[1, :])

[4 3]


#### Terceira linha de todas as colunas

In [113]:
print(l3 := array[2, :])

[5 7]


#### Todas as linhas da primeira coluna

In [88]:
print(result := array[:, 0])

[1 4 5]


#### Todas as linhas da segunda coluna

In [89]:
print(result := array[:, 1])

[2 3 7]


## Matrizes

#### Zeros -> Cria matriz com valores zero

In [90]:
print(zeros := np.zeros([4, 3]))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### Ones -> Cria matriz com valores um

In [91]:
print(ones := np.ones([3, 3]))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### Eye -> Cria matrizquadrada com diagonal principal com valores 1 e os outros como 0

In [92]:
print(eye := np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### Matriz bidimencional

In [93]:
print(mtb := np.array([[7, 2 , 6], [8, 5 ,3], [4, 1, 0]]))

[[7 2 6]
 [8 5 3]
 [4 1 0]]


#### Mostra elemento específico da matriz

In [94]:
print(mtb[0][1])

2


#### Mostra o tamanho das dimenções da matriz

In [95]:
print(mtb.shape)

(3, 3)


## Funções matemáticas

#### Mostra maior valor da matriz

In [96]:
print(mtb.max())

8


#### Mostra menor valor da matriz

In [97]:
print(mtb.min())

0


#### Mostra soma dos elementos da matriz

In [98]:
print(mtb.sum())

36


#### Mostra média dos valores dos elementos da matriz

In [99]:
print(mtb.mean())

4.0


#### Mostra o valor do desvio padrão (standard deviation) dos valores da matriz

In [100]:
print(mtb.std())

2.581988897471611


#### Raiz quadrada

In [101]:
print(np.sqrt(mtb))

[[2.64575131 1.41421356 2.44948974]
 [2.82842712 2.23606798 1.73205081]
 [2.         1.         0.        ]]


#### Exponencial

In [102]:
print(np.exp(mtb))

[[1.09663316e+03 7.38905610e+00 4.03428793e+02]
 [2.98095799e+03 1.48413159e+02 2.00855369e+01]
 [5.45981500e+01 2.71828183e+00 1.00000000e+00]]


## Adição e multiplicação de matrizes

In [103]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[2, 2], [1, 1]])


#### Soma

In [104]:
print(result := (array1 + array2))

[[3 4]
 [4 5]]


#### Multiplicação

In [105]:
print(result := (array1 * array2))

[[2 4]
 [3 4]]


#### Exemplo com quantidades diferentes

In [106]:
array3 = np.array([[2, 3], [ 3, 4], [2, 5]])
array4 = np.array([1, 2])
print(result := (array3 * array4))

[[ 2  6]
 [ 3  8]
 [ 2 10]]


## Valores aleatórios entre zero e um

In [107]:
print(result := np.random.random((5)))

[0.28123393 0.93707314 0.51946141 0.94372673 0.9205465 ]


#### Valores aleatórios contendo números negativos

In [108]:
print(result := np.random.randn((5)))

[-1.52052402 -0.35651826 -0.45015183 -0.19454016 -0.81821184]


#### Matriz 3x4 com números aleatórios multiplicados por 10

In [109]:
print(result := (10 * np.random.random((3, 4))))

[[8.58936806 5.23399625 5.1942005  9.6866233 ]
 [4.72112037 8.21412521 2.03297382 1.41458292]
 [9.84498606 8.51062545 4.26142352 8.98118336]]


## Outra forma de gerar números aleatórios usando semente

In [110]:
rng = np.random.default_rng(1)
randomRng = rng.random(5)
print(randomRng)

[0.51182162 0.9504637  0.14415961 0.94864945 0.31183145]


#### Gerando inteiros

In [111]:
print(result := rng.integers(10, size=(3, 4)))

[[8 4 2 8]
 [2 4 6 5]
 [0 0 8 7]]


## Transposição, rearranja um conjunto de 15 elementos de 0 a 14 em 3 linhas e 5 colunas

In [121]:
print(f := np.arange(15).reshape((3, 5)))


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [120]:
print(result := f.T)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


#### Outra forma de fazer o mesmo resultad

In [122]:
print(result := f.transpose((1, 0)))

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


## Expressões lógicas

In [123]:
print(matrix := np.random.randn(4, 4))

[[-1.30327946 -0.87394817 -0.11693113  1.35518432]
 [-0.52348531  0.77102742  1.30207246  0.31480009]
 [-1.54281017 -0.43030888 -0.45927797 -0.8668207 ]
 [ 0.75102586  1.50030722 -2.60548114 -1.1626978 ]]


#### Valores booleanos

In [125]:
print(boolean := matrix > 0)

[[False False False  True]
 [False  True  True  True]
 [False False False False]
 [ True  True False False]]


#### Where -> Ex: criando matriz com valores -1 e 1 baseados nos valores do array boolean

In [126]:
print(result := np.where(boolean > 0, 1, -1)) # if boolean > 0 = 1 else -1

[[-1 -1 -1  1]
 [-1  1  1  1]
 [-1 -1 -1 -1]
 [ 1  1 -1 -1]]
